apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/akhakpouri/sandbox.git
    targetRevision: HEAD
    path: infra/localstack
  destination:
    server: https://kubernetes.default.svc
    namespace: infra #the desired destination
  syncPolicy:
    automated:
      prune: true #delete all resources no longer in git
      selfHeal: true #overwrite manual cluster changes
    syncOptions:
      - CreateNamespace=true
