apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: infra
  labels:
    app: redis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      initContainers:
        - name: redis-sidecar
          image: oliver006/redis_exporter
          restartPolicy: Always
          ports:
            - containerPort: 9121
      containers:
        - name: redis
          image: redis
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-config
              mountPath: /usr/local/etc/redis
            - name: redis-pvc
              mountPath: /data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: redis-config
          configMap:
            name: redis-app
        - name: redis-pvc
          persistentVolumeClaim:
            claimName: redis-pvc
