apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: infra
spec:
  resources:
    requests:
      storage: 250Mi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
