apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: infra
  labels:
    app: redis-app
spec:
  type: NodePort
  selector:
    app: redis-app
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
    - name: metrics
      protocol: TCP
      port: 9121
      targetPort: 9121
